### ISSUE TITLE
CASA error with TART example data sets

### ISSUE THREAD

**Issue by rubyvanrooyen** [tart-telescope/notebooks#1]
COLAB example notebook [wsclean_TART_MS.ipynb](https://github.com/tart-telescope/notebooks/blob/main/wsclean_TART_MS.ipynb) implementing the README example using WsClean to create an image from generated TART data raised a type error when reading the TIME column
```
An exception occured:
+ >>> Invalid Table data type when accessing column in ScalarColumn ctor for column TIME
```

Using CASA directly raised the same issue in [CASA_TART_workspace.ipynb](https://github.com/tart-telescope/notebooks/blob/main/CASA_TART_workspace.ipynb)

**Comment by rubyvanrooyen** [comment]
It is unclear if the generated MS datasets are outdated or if incompatible versions of the software tools were installed.

The notebooks are overly verbose to show all installation versions

**Comment by tmolteno** [comment]
I think the colab runtime is using version 2.5 of wsclean. On my more recent OS here (Debian) using the later version of wsclean, I get the following output from the notebook

msfile = "tart_data.ms"
!export OPENBLAS_NUM_THREADS=1 && wsclean -v -scale 0.1 -size 1700 1700 -make-psf -pol RR  -use-wgridder -auto-threshold 3 -mgain 0.05 -gain 0.05 -niter 2000 {msfile}

`WSClean version 3.1.0 (2022-04-01)
This software package is released under the GPL version 3.
Author: André Offringa (offringa@gmail.com).

Number of threads selected: 4
Using image size of 1700 x 1700, padded to 2040 x 2040.
No corrected data in first measurement set: tasks will be applied on the data column.
Total nr of channels found in measurement sets: 1
=== IMAGING TABLE ===
       # Pol Ch JG ²G FG FI In Freq(MHz)
| Independent group:
+-+-J- 0  RR   0  0  0  0  0  0  1574-1577 (1)

Reordering tart_data.ms into 1 x 1 parts.
Reordering: 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Total selected rows: 276
Initializing model visibilities: 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
 == Constructing PSF ==
Precalculating weights for uniform weighting...
Opening reordered part 0 spw 0 for tart_data.ms
Detected 7.7 GB of system memory, usage not limited.
Opening reordered part 0 spw 0 for tart_data.ms
Selected channels: 0-1
Determining min and max w & theoretical beam size... DONE (w=[0:0] lambdas, maxuvw=13.7947 lambda)
Theoretic beam = 4.15 deg
Minimal inversion size: 99 x 99, using optimal: 100 x 100
Max 205559908 rows fit in memory.
Loading data in memory...
Gridding 276 rows...
Gridded visibility count: 276
Trimming 2040 x 2040 -> 1700 x 1700
Normalized PSF by factor of 1.00026.
Fitting beam... major=3.61 deg, minor=3.29 deg, PA=72.36 deg, theoretical=4.15 deg.
Writing psf image... DONE
Storing wsclean-psf-RR-tmp.fits
 == Constructing image ==
Opening reordered part 0 spw 0 for tart_data.ms
Selected channels: 0-1
Max 205559908 rows fit in memory.
Loading data in memory...
Gridding 276 rows...
Gridded visibility count: 276
Trimming 2040 x 2040 -> 1700 x 1700
Storing wsclean-residual-RR-tmp.fits
Storing wsclean-model-RR-tmp.fits
Loading wsclean-residual-RR-tmp.fits
Writing dirty image...
 == Deconvolving (1) ==
Loading residual images...
Loading wsclean-residual-RR-tmp.fits
Loading model images...
Loading wsclean-model-RR-tmp.fits`

**Comment by tmolteno** [comment]
I will see if I can figure out why wsclean is reading the TIME column of the MAIN table incorrectly. I'll double check that casa can open the measurement sets...

**Comment by tmolteno** [comment]
Seems to be related to Issue #7 in github.com/tart-telescope/tart2ms. Testing this as a fix now.

**Comment by tmolteno** [comment]
This issue seems to have been fixed in the latest tart2ms release which was modified based on this bug report. (The new version v0.1.3b4 is now available on pypi)!
