### ISSUE TITLE
The adding of the ppa for kernsuite causes a wait on Enter

### ISSUE THREAD

**Issue by tmolteno** [tart-telescope/notebooks#2]
adding a -y option to the command

!add-apt-repository -y -s ppa:kernsuite/kern-7

Seems to fix the issue on colab.

**Comment by rubyvanrooyen** [comment]
Fixed in updated notebook [wsclean_TART_MS.ipynb](https://github.com/tart-telescope/notebooks/blob/main/application/wsclean_TART_MS.ipynb)
